version: '3'
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'songdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DATABASE_HOST: database

volumes:
  db_data:
